// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  key_services: dynamic(() => import("./KeyServices")),
  no_image: dynamic(() => import("./NoImage")),
  working_with: dynamic(() => import("./WorkingWith")),
};
